services:
  kanatomo:
    image: kanatomo
    build:
      context: .
      dockerfile: KanaTomo/Dockerfile
    ports:
      - "5070:80"
    environment:
      - ApiBaseUrl=http://host.docker.internal:5070/api/v1/translate
    extra_hosts:
      - "host.docker.internal:host-gateway"